export const CLASSES_SUCCESS = 'CLASSES_SUCCESS';
export const CLASSES_FAIL = 'CLASSES_FAIL';

export const SET_AUTH_LOADING = 'SET_AUTH_LOADING';

export const REMOVE_AUTH_LOADING = 'REMOVE_AUTH_LOADING';