export const CLASSES_LIST_SUCCESS = 'CLASSES_LIST_SUCCESS';
export const CLASSES_LIST_FAIL = 'CLASSES_LIST_FAIL';

export const SET_AUTH_LOADING = 'SET_AUTH_LOADING';

export const REMOVE_AUTH_LOADING = 'REMOVE_AUTH_LOADING';