export const UPDATE_CLA_SUCCESS = 'UPDATE_CLA_SUCCESS';
export const UPDATE_CLA_FAIL = 'UPDATE_CLA_FAIL';

export const SET_AUTH_LOADING = 'SET_AUTH_LOADING';

export const REMOVE_AUTH_LOADING = 'REMOVE_AUTH_LOADING';