export const CREATE_UP_SUCCESS = 'CREATE_UP_SUCCESS';
export const CREATE_UP_FAIL = 'CREATE_UP_FAIL';

export const SET_AUTH_LOADING = 'SET_AUTH_LOADING';

export const REMOVE_AUTH_LOADING = 'REMOVE_AUTH_LOADING';