export const MEMBERSHIP_SUCCESS = 'MEMBERSHIP_SUCCESS';
export const MEMBERSHIP_FAIL = 'MEMBERSHIP_FAIL';

export const SET_AUTH_LOADING = 'SET_AUTH_LOADING';

export const REMOVE_AUTH_LOADING = 'REMOVE_AUTH_LOADING';