export const DELETE_MEM_SUCCESS = 'DELETE_MEM_SUCCESS';
export const DELETE_MEM_FAIL = 'DELETE_MEM_FAIL';

export const SET_AUTH_LOADING = 'SET_AUTH_LOADING';

export const REMOVE_AUTH_LOADING = 'REMOVE_AUTH_LOADING';