export const CREATE_UC_SUCCESS = 'CREATE_UC_SUCCESS';
export const CREATE_UC_FAIL = 'CREATE_UC_FAIL';

export const SET_AUTH_LOADING = 'SET_AUTH_LOADING';

export const REMOVE_AUTH_LOADING = 'REMOVE_AUTH_LOADING';