export const MEMBERSHIPS_SUCCESS = 'MEMBERSHIPS_SUCCESS';
export const MEMBERSHIPS_FAIL = 'MEMBERSHIPS_FAIL';

export const SET_AUTH_LOADING = 'SET_AUTH_LOADING';

export const REMOVE_AUTH_LOADING = 'REMOVE_AUTH_LOADING';