export const UPDATE_MEM_SUCCESS = 'UPDATE_MEM_SUCCESS';
export const UPDATE_MEM_FAIL = 'UPDATE_MEM_FAIL';

export const SET_AUTH_LOADING = 'SET_AUTH_LOADING';

export const REMOVE_AUTH_LOADING = 'REMOVE_AUTH_LOADING';