export const DELETE_CLA_SUCCESS = 'DELETE_CLA_SUCCESS';
export const DELETE_CLA_FAIL = 'DELETE_CLA_FAIL';

export const SET_AUTH_LOADING = 'SET_AUTH_LOADING';

export const REMOVE_AUTH_LOADING = 'REMOVE_AUTH_LOADING';